### ISSUE TITLE
Error: TypeError: response.choices is undefined

### ISSUE THREAD

**Issue by channingb** [alikon/testcom#11]
Hello. 

Just installed OpenAI. Am getting this response when I select the button in an article.
TypeError: response.choices is undefined

I installed API as per instructions.

Note, the articles I am using this for are in a category blog. Not sure this should matter.
Thank you.

Channing

**Comment by alikon** [comment]
hello
thanks for reporting
can you share privately your api key only for debugging purpose ?
send me an email

**Comment by channingb** [comment]
Hi Sir:

Just received an email form Open AI.  They requested I create a new API key.  I did, still have the same message.  The message is at the bottom of this comment.

Perhaps a more information might help.  We are moving a web site to a new platform, Joomla.  The site is all under "Registered" access.  However, I test by making the index.php "Public" and the article I am testing as "Public."  Not sure if this brings light to our challenge.

Email received:

Hi there,
We have determined that your OpenAI API key "Marra" (sk-5Tn...C8V) was leaked, and have disabled it with immediate effect.
This may be because you committed your API key to an online service such as GitHub, or your key may have been compromised in another way.
Head over to the [API Keys](https://mandrillapp.com/track/click/31165340/platform.openai.com?p=eyJzIjoiVzFPdWI5M1RfNTFudnZna3piNWpHZjBEUm9JIiwidiI6MSwicCI6IntcInVcIjozMTE2NTM0MCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3BsYXRmb3JtLm9wZW5haS5jb21cXFwvYWNjb3VudFxcXC9hcGkta2V5c1wiLFwiaWRcIjpcImI3NzNmZjY0YTk0ODQyMTc4NGVjMTg1YzA0YTJhOGU2XCIsXCJ1cmxfaWRzXCI6W1wiZGRlMTIyMmY1ZjBmNGVlOWEwNGY2NzdkZDQ2N2ZjN2MyNTllN2U4MFwiXX0ifQ) page to create a new API key.
If your API key was stored in any locations–for instance, in code you are running–it will need to be updated before you can run this code again.
Finally, we ask that you please review our help center guides on [Best practices for API key safety](https://mandrillapp.com/track/click/31165340/help.openai.com?p=eyJzIjoiZnIyMGVsU0JNU3paZ2w3R0k3OTFGUGltX0tFIiwidiI6MSwicCI6IntcInVcIjozMTE2NTM0MCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2hlbHAub3BlbmFpLmNvbVxcXC9lblxcXC9hcnRpY2xlc1xcXC81MTEyNTk1LWJlc3QtcHJhY3RpY2VzLWZvci1hcGkta2V5LXNhZmV0eVwiLFwiaWRcIjpcImI3NzNmZjY0YTk0ODQyMTc4NGVjMTg1YzA0YTJhOGU2XCIsXCJ1cmxfaWRzXCI6W1wiNzI4ODA0ZmM5MzY4OWEyZTk2MDE2ZDNhYzYyZjhmZGY0MTc5MGJkOVwiXX0ifQ) and [Preventing unauthorized usage](https://mandrillapp.com/track/click/31165340/help.openai.com?p=eyJzIjoiamEyV0RoZ21BNmFSazM2RTlvakVVdW5LeDJRIiwidiI6MSwicCI6IntcInVcIjozMTE2NTM0MCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2hlbHAub3BlbmFpLmNvbVxcXC9lblxcXC9hcnRpY2xlc1xcXC84MzA0Nzg2LXByZXZlbnRpbmctdW5hdXRob3JpemVkLXVzYWdlXCIsXCJpZFwiOlwiYjc3M2ZmNjRhOTQ4NDIxNzg0ZWMxODVjMDRhMmE4ZTZcIixcInVybF9pZHNcIjpbXCJmYzY3MzdjMDQ5MTM2Y2U4ZjZkYjQ0NjM2NzA0NDdkZWQxY2YzNzM1XCJdfSJ9).
Best,
The OpenAI team

**Comment by alikon** [comment]
😮‍💨
