### ISSUE TITLE
Task - Delete Trashed 1.6 create super user cliagent

### ISSUE THREAD

**Issue by ssnobben** [alikon/testcom#13]
Hi your plugin create a super user cliagent with email aa@aa.it  and I wonder why your plugin doing this??

Seems like a hacker attempt and its blocking by Admin Tools pro though.. hmm
-------------------------------------------------------------------------------------------
Hello,
Planned execution of Scheduled Task#12, Delete trashed items, has failed with exit code 5 at Monday, 06 May 2024 09:25.
Please visit the Joomla! backend for more information.
---------------------------------------------------------------------------------------------
"Hello,

We would like to notify you that we detected the suspicious addition of one or more Super User accounts to your site. These new Super User accounts do not seem to have been created through the regular means, i.e. Joomla's “Users” page. Therefore they have been blocked. The new Super User accounts detected and blocked are:

    #1197 – cliagent – cliagent <aa@aa.it>

Do I need to worry?

Super User accounts have full access to your site. They can modify all content, without any restriction. They can also install software which can access or modify every aspect of your site, including arbitrary files, database content and configuration settings. Only grant Super User access to people you trust.

If you are receiving this email it means that these Super User accounts were created outside Joomla's “Users” page. Typically this means that a hacker found a way to bypass your site's or your server's security and tried to surreptitiously create Super User accounts for themselves. For this reason these accounts were blocked, i.e. they cannot be used to log into your site.

It is possible, however, that you do receive this email in error: if you or another Super User did intend to create these Super User accounts and used a third party tool to do that. If this is the case then do not worry. Just log in to your site's administrator backend with your own Super User account, go to the Users page, edit the users listed further above in this email and unblock them.

If you or another Super User did NOT intend to create these Super Users we recommend auditing your site and your server for any other signs of anomalous activity."

**Comment by alikon** [comment]
no need to worry cause the superuser is created only for ACL to delete trashed items and then deleted

**Comment by alikon** [comment]
the CLI nor the Webcron nor the Lazy have user privileges to "DELETE" items

**Comment by brbrbr** [comment]
When ever the task crashes, your plugin leaves a root user with known password on a system.

This can easily be resolved with  UserHelper::genRandomPassword() for the admin_password_plain

**Comment by alikon** [comment]
pull request are wellcome

**Comment by brbrbr** [comment]
You could take it even a step further and autonaticly search for an existing super user.

**Comment by alikon** [comment]
done in the [1.7.0](https://raw.githubusercontent.com/alikon/testcom/main/plugins/task/deltrash/plg_task_deltrash-1.7.0.zip)  use an existing superuser

**Comment by ssnobben** [comment]
Great!
