### ISSUE TITLE
Meta

### ISSUE THREAD

**Issue by aetherwizard** [alikon/testcom#9]
Open AI Meta Description shows signs of starting up, but no meta description appears. The API key was entered, and to be sure the key was good, a fresh key was generated.

**Comment by alikon** [comment]
can you check the browser console ? and report back please

**Comment by aetherwizard** [comment]
Here is the output in my console after doing a reboot of my system and
browser:


Searching for plugin objects...
content-script.js:95 Failed to get subsystem status for purpose Object
content-script.js:95 Failed to get subsystem status for purpose Object
Grammarly.js:2 Debug reports have been enabled
enableHistoryLoggerInProd @ Grammarly.js:2
main.min.js?1.9.10:2 Route 66 SEO analysis worker initialized
content-script.js:95 Failed to get subsystem status for purpose Object
content-script.js:95 Failed to get subsystem status for purpose Object
commons.js:2 Channel: Error in handleResponse UNK/SW_UNREACHABLE
isLogsEnabled null
_handleResponsePromise @ commons.js:2
2commons.js:2 Channel: Error in handleResponse UNK/SW_UNREACHABLE options
getValues
_handleResponsePromise @ commons.js:2
commons.js:2 Channel: Error in handleResponse UNK/SW_UNREACHABLE
contextMenu createContextMenu
_handleResponsePromise @ commons.js:2
commons.js:2 Channel: Error in handleResponse UNK/SW_UNREACHABLE tabClipper
initCompleted
_handleResponsePromise @ commons.js:2
2commons.js:2 Channel: Error in handleResponse UNK/SW_UNREACHABLE options
getValue
_handleResponsePromise @ commons.js:2
3/administrator/index…layout=edit&id=5#:1 Uncaught (in promise) Error:
Could not establish connection. Receiving end does not exist.
2commons.js:2 Uncaught (in promise) Error: Could not establish connection.
Receiving end does not exist.
2/administrator/index…layout=edit&id=5#:1 Uncaught (in promise) Error:
Could not establish connection. Receiving end does not exist.
DevTools failed to load source map: Could not load content for
https://sota.aetherwizard.com/media/route66/js/seo/main.min.js.map: HTTP
error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for
chrome-extension://llpahfhchhlfdigfpeimeagojnkgeice/js/purify.js.map:
System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for
chrome-extension://llpahfhchhlfdigfpeimeagojnkgeice/js/popper.min.js.map:
System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for
chrome-extension://llpahfhchhlfdigfpeimeagojnkgeice/js/tippy-bundle.umd.min.js.map:
System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for
https://sota.aetherwizard.com/media/route66/js/seo/worker.min.js.map: Fetch
through target failed: Target not supported; Fallback: HTTP error: status
code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
index.php?option=com_content&view=article&layout=edit&id=5:916     POST
https://api.openai.com/v1/completions 400
cambia @ index.php?option=com_content&view=article&layout=edit&id=5:916
commons.js:2 Channel: Error in handleResponse UNK/SW_UNREACHABLE
contextMenu createContextMenu
_handleResponsePromise @ commons.js:2
(anonymous) @ commons.js:2
Promise.catch (async)
_sendMessageToExtension @ commons.js:2
sendToExtension @ commons.js:2
send @ commons.js:2
setContextMenuItem @ commons.js:2
Be @ commons.js:2
commons.js:2 Uncaught (in promise) Error: Could not establish connection.
Receiving end does not exist.
fromGeneric @ commons.js:2
fromAny @ commons.js:2
_handleResponsePromise @ commons.js:2
(anonymous) @ commons.js:2
Promise.catch (async)
_sendMessageToExtension @ commons.js:2
sendToExtension @ commons.js:2
send @ commons.js:2
setContextMenuItem @ commons.js:2
Be @ commons.js:2
commons.js:2 Channel: Error in handleResponse UNK/SW_UNREACHABLE tabClipper
checkBackgroundStatus
_handleResponsePromise @ commons.js:2
(anonymous) @ commons.js:2
Promise.catch (async)
_sendMessageToExtension @ commons.js:2
sendToExtension @ commons.js:2
Le @ commons.js:2
Be @ commons.js:2
commons.js:2 Channel: Error in handleResponse UNK/SW_UNREACHABLE
contextMenu createContextMenu
_handleResponsePromise @ commons.js:2
(anonymous) @ commons.js:2
Promise.catch (async)
_sendMessageToExtension @ commons.js:2
sendToExtension @ commons.js:2
send @ commons.js:2
setContextMenuItem @ commons.js:2
Be @ commons.js:2
commons.js:2 Channel: Error in handleResponse UNK/SW_UNREACHABLE tabClipper
checkBackgroundStatus
_handleResponsePromise @ commons.js:2
(anonymous) @ commons.js:2
Promise.catch (async)
_sendMessageToExtension @ commons.js:2
sendToExtension @ commons.js:2
Le @ commons.js:2
Be @ commons.js:2
commons.js:2 Uncaught (in promise) Error: Could not establish connection.
Receiving end does not exist.
fromGeneric @ commons.js:2
fromAny @ commons.js:2
_handleResponsePromise @ commons.js:2
(anonymous) @ commons.js:2
Promise.catch (async)
_sendMessageToExtension @ commons.js:2
sendToExtension @ commons.js:2
send @ commons.js:2
setContextMenuItem @ commons.js:2
Be @ commons.js:2
commons.js:2 Channel: Error in handleResponse UNK/SW_UNREACHABLE
contextMenu createContextMenu
_handleResponsePromise @ commons.js:2
(anonymous) @ commons.js:2
Promise.catch (async)
_sendMessageToExtension @ commons.js:2
sendToExtension @ commons.js:2
send @ commons.js:2
listener @ commons.js:2
commons.js:2 Uncaught (in promise) Error: Could not establish connection.
Receiving end does not exist.
fromGeneric @ commons.js:2
fromAny @ commons.js:2
_handleResponsePromise @ commons.js:2
(anonymous) @ commons.js:2
Promise.catch (async)
_sendMessageToExtension @ commons.js:2
sendToExtension @ commons.js:2
send @ commons.js:2
listener @ commons.js:2
2commons.js:2 Channel: Error in handleResponse UNK/SW_UNREACHABLE
broadcastEventToTab clipper_state_changed
_handleResponsePromise @ commons.js:2
(anonymous) @ commons.js:2
Promise.catch (async)
_sendMessageToExtension @ commons.js:2
sendToExtension @ commons.js:2
(anonymous) @ commons.js:2
Promise.then (async)
ne @ commons.js:2
(anonymous) @ commons.js:2
Promise.catch (async)
Le @ commons.js:2
Be @ commons.js:2
2commons.js:2 Uncaught (in promise) Error: Could not establish connection.
Receiving end does not exist.

David Thomson

**Comment by vladisov1** [comment]
I have to say that I don't like it either. The wheel spins and nothing

**Comment by alikon** [comment]
please update to the latest version [1.1.0](https://raw.githubusercontent.com/alikon/testcom/main/plugins/content/aimetadesc/plg_content_aimetadesc-1.1.0.zip)
